### ISSUE TITLE
Thumbnail Image view does not render in landing page

### ISSUE THREAD

**Issue by randhirkumar65** [TeaTalkInternal/NewsMeUp#1]

**Comment by randhirkumar65** [comment]
@vishalkevin11 can i work on this issue?

**Comment by randhirkumar65** [comment]
@vishalkevin11 Opened a FIX for above issue https://github.com/TeaTalkInternal/NewsMeUp/pull/2

**Comment by vishalkevin11** [comment]
@randhirkumar65 Looks good to me.
